apiVersion: apps/v1
kind: Deployment
metadata:
  name: "lcm-blue"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "lcm"
  template:
    metadata:
      labels:
        app: "lcm"
    spec:
      containers:
        - name: "lcm"
          image: "lottechemicalacr.azurecr.io/php"
          ports:
            - containerPort: 80
